### ISSUE TITLE
Reactive Form Control Example

### ISSUE THREAD

**Issue by slamkajs** [jwelker110/file-input-accessor#3] opened 2019-01-11 04:11 UTC
Following the guidance of the README to utilize the FormControl functionality, I received the following error:
```ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.```

To overcome this error I updated ```this.fileControl.setValue([])``` to ```this.fileControl.patchValue('', { emitEvent: false })```.

**Comment by jwelker110** [comment] 2019-01-11 12:49
Welcome, thank you for taking the time to reach out.

I created a new project using `@angular/cli~7.2.1` but I'm not able to reproduce the error. 

Typically when I've received an error like this, I've been able to track the issue down to how I'm handling an Observable. 

I suspect it is related to the form control's valueChanges property, since not emitting the changes "fixes" the problem, I think this is the first place to look.

I'd like more information so I can work on reproducing the error and narrow down the cause:

- What version of Angular and what version of this package you are using? 
- Could you show me more of the surrounding code? Where you subscribe to valueChanges, any type of form Validators you are using (if custom, the code would be helpful), and the template code as well, so I can see which properties on the input are being used and how?

Thank you for your time.

**Comment by jwelker110** [comment] 2019-01-20 13:15
@slamkajs any update on this? Were you able to determine the cause of the error in your application at least?

**Comment by jwelker110** [comment] 2019-01-23 11:09
Closing since I'm not able to determine the cause of the error with the information available.

**Closed as completed by jwelker110** 2019-01-23 11:09 UTC
